### ISSUE TITLE
LUIS Intents alignment with Cognitive Kiosk Application

### ISSUE THREAD

**Issue by SKApretto71** [Microsoft/BikeSharing360_BotApps#1]
In Cognitive Kiosk Application code, the interactive session leverages LUIS to get the Intents from the authenticated person. The LUIS application to be used is the same as the BotApps repository.

Unfortunately, the code is referencing Intent names that are different from the ones in LUIS application, with the results that the system does noty work as expected until one of the two is manually changed.

Appears a misalignment in versions from C# code to Luis code.

**Comment by xiangyan99** [comment]
Thanks for reporting the issue. A fix has been checked in.
