### ISSUE TITLE
CustomerServiceApi project is empty

### ISSUE THREAD

**Issue by SKApretto71** [Microsoft/BikeSharing360_BotApps#3]
Hi,
trying the bot I saw that the project "CurtomerServiceAPi" appears empty, with code alike the following just returning empty/null values. Is there a version with some more code available, at least to replicate the use cases and data used in Connect() keynote?

        [Route("lookupuser")]
        [HttpGet]
        public string LookupUser(string ctype, string value)
        {
            //look up user from the database
            return "";
        }

**Comment by xiangyan99** [comment]
Some default value has been added.
